// import { Client } from './types';

// // Datos mock: 50 clientes completos
// export const mockClients: Client[][] = [
//   [
//     // ───────── Client 01
//     {
//       id: 'test',
//       name: 'Lucas',
//       lastName: 'Gómez',
//       dni: '30000001',
//       age: 23,
//       gender: 'M',
//       email: 'lucas.gomez@example.com',
//       phone: '+54 9 263 2001‑0001',
//       birthDate: new Date('2001-01-03'),
//       creationDate: new Date('2025-04-26'),
//       isActive: false,
//       photo: '/photos/lucas_gomez.jpg',
//       isInsured: false,
//       activities: [
//         {
//           activityName: 'Yoga',
//           attendedLocation: 'Sede Norte',
//           attendedDays: 'Lunes, miercoles y viernes 18:30',
//           goal: 'Cardio',
//           creationDate: new Date('2025-04-26'),
//           clientId: '30000001',
//         },
//       ],
//       healthData: {
//         clientId: '30000001',
//         healthInsurance: '',
//         weight: 66,
//         height: 1.58,
//         currentStudies: '',
//         bloodPressure: '120/80',
//         diseases: '',
//         medications: '',
//         smoker: false,
//         studyImages: [],
//         boneIssues: '',
//       },
//     },
//     // ───────── Client 02
//     {
//       id: 'test',
//       name: 'Martina',
//       lastName: 'Pérez',
//       dni: '30000002',
//       age: 39,
//       gender: 'F',
//       email: 'martina.perez@example.com',
//       phone: '+54 9 88 2001‑0002',
//       birthDate: new Date('1985-05-01'),
//       creationDate: new Date('2025-03-14'),
//       isActive: false,
//       photo: '/photos/martina_perez.jpg',
//       isInsured: true,
//       activities: [
//         {
//           activityName: 'Funcional',
//           attendedLocation: 'Sede Norte',
//           attendedDays: 'Lunes, miercoles y viernes 18:30',
//           goal: 'Triatlón',
//           creationDate: new Date('2025-03-14'),
//           clientId: '30000002',
//         },
//       ],
//       healthData: {
//         clientId: '30000002',
//         healthInsurance: 'Medifé',
//         weight: 60,
//         height: 1.7,
//         currentStudies: '',
//         bloodPressure: '120/80',
//         diseases: '',
//         medications: '',
//         smoker: true,
//         studyImages: [],
//         boneIssues: '',
//       },
//     },
//     // ───────── Client 03
//     {
//       id: 'test',
//       name: 'Sofía',
//       lastName: 'Rossi',
//       dni: '30000003',
//       age: 18,
//       gender: 'F',
//       email: 'sofia.rossi@example.com',
//       phone: '+54 9 182 2001‑0003',
//       birthDate: new Date('2005-07-10'),
//       creationDate: new Date('2025-03-06'),
//       isActive: true,
//       photo: '/photos/sofia_rossi.jpg',
//       isInsured: false,
//       activities: [
//         {
//           activityName: 'Funcional',
//           attendedLocation: 'Parque Independencia',
//           attendedDays: 'Lunes, miercoles y viernes 18:30',
//           goal: 'Cardio',
//           creationDate: new Date('2025-03-06'),
//           clientId: '30000003',
//         },
//       ],
//       healthData: {
//         clientId: '30000003',
//         healthInsurance: '',
//         weight: 80,
//         height: 1.63,
//         currentStudies: '',
//         bloodPressure: '120/80',
//         diseases: '',
//         medications: '',
//         smoker: true,
//         studyImages: [],
//         boneIssues: '',
//       },
//     },
//     // ───────── Client 04
//     {
//       id: 'test',
//       name: 'Tomás',
//       lastName: 'Luna',
//       dni: '30000004',
//       age: 35,
//       gender: 'M',
//       email: 'tomas.luna@example.com',
//       phone: '+54 9 306 2001‑0004',
//       birthDate: new Date('1989-10-18'),
//       creationDate: new Date('2025-01-30'),
//       isActive: true,
//       photo: '/photos/tomas_luna.jpg',
//       isInsured: false,
//       activities: [
//         {
//           activityName: 'Natación',
//           attendedLocation: 'Sede Sur',
//           attendedDays: 'Lunes, miercoles y viernes 18:30',
//           goal: 'Diversión',
//           creationDate: new Date('2025-01-30'),
//           clientId: '30000004',
//         },
//       ],
//       healthData: {
//         clientId: '30000004',
//         healthInsurance: '',
//         weight: 77,
//         height: 1.64,
//         currentStudies: '',
//         bloodPressure: '120/80',
//         diseases: '',
//         medications: '',
//         smoker: true,
//         studyImages: [],
//         boneIssues: '',
//       },
//     },
//     // ───────── Client 05
//     {
//       id: 'test',
//       name: 'Valentina',
//       lastName: 'Fernández',
//       dni: '30000005',
//       age: 19,
//       gender: 'F',
//       email: 'valentina.fernandez@example.com',
//       phone: '+54 9 30 2001‑0005',
//       birthDate: new Date('2005-09-25'),
//       creationDate: new Date('2025-04-12'),
//       isActive: false,
//       photo: '/photos/valentina_fernandez.jpg',
//       isInsured: true,
//       activities: [
//         {
//           activityName: 'Spinning',
//           attendedLocation: 'Plaza Abierta',
//           attendedDays: 'Lunes, miercoles y viernes 18:30',
//           goal: 'Dominadas',
//           creationDate: new Date('2025-04-12'),
//           clientId: '30000005',
//         },
//       ],
//       healthData: {
//         clientId: '30000005',
//         healthInsurance: 'OSDE 410',
//         weight: 92,
//         height: 1.67,
//         currentStudies: '',
//         bloodPressure: '120/80',
//         diseases: '',
//         medications: '',
//         smoker: false,
//         studyImages: [],
//         boneIssues: '',
//       },
//     },
//     // ───────── Client 06
//     {
//       id: 'test',
//       name: 'Diego',
//       lastName: 'Martínez',
//       dni: '30000006',
//       age: 37,
//       gender: 'M',
//       email: 'diego.martinez@example.com',
//       phone: '+54 9 79 2001‑0006',
//       birthDate: new Date('1987-04-18'),
//       creationDate: new Date('2025-01-27'),
//       isActive: false,
//       photo: '/photos/diego_martinez.jpg',
//       isInsured: true,
//       activities: [
//         {
//           activityName: 'Musculación',
//           attendedLocation: 'Sede Norte',
//           attendedDays: 'Lunes, miercoles y viernes 18:30',
//           goal: 'Triatlón',
//           creationDate: new Date('2025-01-27'),
//           clientId: '30000006',
//         },
//       ],
//       healthData: {
//         clientId: '30000006',
//         healthInsurance: 'OSDE 210',
//         weight: 90,
//         height: 1.67,
//         currentStudies: '',
//         bloodPressure: '120/80',
//         diseases: '',
//         medications: '',
//         smoker: false,
//         studyImages: [],
//         boneIssues: '',
//       },
//     },
//     // ───────── Client 07
//     {
//       id: 'test',
//       name: 'Carla',
//       lastName: 'Nuñez',
//       dni: '30000007',
//       age: 25,
//       gender: 'F',
//       email: 'carla.nunez@example.com',
//       phone: '+54 9 374 2001‑0007',
//       birthDate: new Date('1999-11-19'),
//       creationDate: new Date('2025-02-11'),
//       isActive: true,
//       photo: '/photos/carla_nunez.jpg',
//       isInsured: false,
//       activities: [
//         {
//           activityName: 'Pilates',
//           attendedLocation: 'Piscina Olímpica',
//           attendedDays: 'Lunes, miercoles y viernes 18:30',
//           goal: 'Hipertrofia',
//           creationDate: new Date('2025-02-11'),
//           clientId: '30000007',
//         },
//       ],
//       healthData: {
//         clientId: '30000007',
//         healthInsurance: '',
//         weight: 67,
//         height: 1.87,
//         currentStudies: '',
//         bloodPressure: '120/80',
//         diseases: '',
//         medications: '',
//         smoker: false,
//         studyImages: [],
//         boneIssues: '',
//       },
//     },
//     // ───────── Client 08
//     {
//       id: 'test',
//       name: 'Gonzalo',
//       lastName: 'Ibarra',
//       dni: '30000008',
//       age: 24,
//       gender: 'M',
//       email: 'gonzalo.ibarra@example.com',
//       phone: '+54 9 145 2001‑0008',
//       birthDate: new Date('2000-04-17'),
//       creationDate: new Date('2025-03-05'),
//       isActive: true,
//       photo: '/photos/gonzalo_ibarra.jpg',
//       isInsured: false,
//       activities: [
//         {
//           activityName: 'Spinning',
//           attendedLocation: 'Parque Independencia',
//           attendedDays: 'Lunes, miercoles y viernes 18:30',
//           goal: 'Dominadas',
//           creationDate: new Date('2025-03-05'),
//           clientId: '30000008',
//         },
//       ],
//       healthData: {
//         clientId: '30000008',
//         healthInsurance: '',
//         weight: 66,
//         height: 1.55,
//         currentStudies: '',
//         bloodPressure: '120/80',
//         diseases: '',
//         medications: '',
//         smoker: false,
//         studyImages: [],
//         boneIssues: '',
//       },
//     },
//     // ───────── Client 09
//     {
//       id: 'test',
//       name: 'Agustina',
//       lastName: 'Ruiz',
//       dni: '30000009',
//       age: 19,
//       gender: 'F',
//       email: 'agustina.ruiz@example.com',
//       phone: '+54 9 353 2001‑0009',
//       birthDate: new Date('2005-11-16'),
//       creationDate: new Date('2025-04-25'),
//       isActive: false,
//       photo:
//         'https://primefaces.org/cdn/primeng/images/galleria/galleria10.jpg',
//       isInsured: true,
//       activities: [
//         {
//           activityName: 'Gimnasio',
//           attendedLocation: 'Rivadavia',
//           attendedDays: 'Lunes, miercoles y viernes 18:30',
//           goal: 'Dominadas',
//           creationDate: new Date('2025-04-25'),
//           clientId: '30000009',
//         },
//         {
//           activityName: 'Basquet',
//           attendedLocation: 'Rivadavia',
//           attendedDays: 'Lunes, miercoles y viernes 18:30',
//           goal: 'Cardio',
//           creationDate: new Date('2025-04-26'),
//           clientId: '30000001',
//         },
//         {
//           activityName: 'Funcional',
//           attendedLocation: 'Rivadavia',
//           attendedDays: 'Lunes, miercoles y viernes 18:30',
//           goal: 'Cardio',
//           creationDate: new Date('2025-04-26'),
//           clientId: '30000001',
//         },
//       ],
//       healthData: {
//         clientId: '30000009',
//         healthInsurance: 'OSDE 210',
//         weight: 67,
//         height: 1.83,
//         currentStudies: 'Ergonometria, Electrocardiograma',
//         bloodPressure: 'NORMAL',
//         diseases: 'Ninguna',
//         medications: 'Ibupreno 900, Paracetamol 500',
//         smoker: true,
//         studyImages: [
//           'https://surveyheartmedia.s3.ap-south-1.amazonaws.com/files/2d41ee13fda5c3895e8df0c45d07b5/63fbb76e2350a126ca4b7df5/sh_1678387483977.jpg',
//           'https://surveyheartmedia.s3.ap-south-1.amazonaws.com/files/2d41ee13fda5c3895e8df0c45d07b5/63fbb76e2350a126ca4b7df5/sh_1678410405289.jpg',
//           'https://surveyheartmedia.s3.ap-south-1.amazonaws.com/files/2d41ee13fda5c3895e8df0c45d07b5/63fbb76e2350a126ca4b7df5/sh_1678661953194.jpg',
//         ],
//         boneIssues: 'Ligamentos cruzados',
//       },
//     },
//     // ───────── Client 10
//     {
//       id: 'test',
//       name: 'Nicolás',
//       lastName: 'Silva',
//       dni: '30000010',
//       age: 35,
//       gender: 'M',
//       email: 'nicolas.silva@example.com',
//       phone: '+54 9 259 2001‑0010',
//       birthDate: new Date('1989-10-24'),
//       creationDate: new Date('2025-02-22'),
//       isActive: false,
//       photo: '/photos/nicolas_silva.jpg',
//       isInsured: true,
//       activities: [
//         {
//           activityName: 'Musculación',
//           attendedLocation: 'Piscina Olímpica',
//           attendedDays: 'Lunes, miercoles y viernes 18:30',
//           goal: 'Cardio',
//           creationDate: new Date('2025-02-22'),
//           clientId: '30000010',
//         },
//       ],
//       healthData: {
//         clientId: '30000010',
//         healthInsurance: 'Swiss Medical',
//         weight: 58,
//         height: 1.59,
//         currentStudies: '',
//         bloodPressure: '120/80',
//         diseases: '',
//         medications: '',
//         smoker: false,
//         studyImages: [],
//         boneIssues: '',
//       },
//     },
//     // ───────── Client 11
//     {
//       id: 'test',
//       name: 'Fernando',
//       lastName: 'Torres',
//       dni: '30000011',
//       age: 25,
//       gender: 'M',
//       email: 'fernando.torres@example.com',
//       phone: '+54 9 130 2001‑0011',
//       birthDate: new Date('1999-01-14'),
//       creationDate: new Date('2025-01-19'),
//       isActive: true,
//       photo: '/photos/fernando_torres.jpg',
//       isInsured: true,
//       activities: [
//         {
//           activityName: 'Running',
//           attendedLocation: 'Plaza Abierta',
//           attendedDays: 'Lunes, miercoles y viernes 18:30',
//           goal: 'Dominadas',
//           creationDate: new Date('2025-01-19'),
//           clientId: '30000011',
//         },
//       ],
//       healthData: {
//         clientId: '30000011',
//         healthInsurance: 'OSDE 410',
//         weight: 91,
//         height: 1.71,
//         currentStudies: '',
//         bloodPressure: '120/80',
//         diseases: '',
//         medications: '',
//         smoker: true,
//         studyImages: [],
//         boneIssues: '',
//       },
//     },
//     // ───────── Client 12
//     {
//       id: 'test',
//       name: 'Julieta',
//       lastName: 'Romero',
//       dni: '30000012',
//       age: 28,
//       gender: 'F',
//       email: 'julieta.romero@example.com',
//       phone: '+54 9 75 2001‑0012',
//       birthDate: new Date('1996-03-26'),
//       creationDate: new Date('2025-04-08'),
//       isActive: false,
//       photo: '/photos/julieta_romero.jpg',
//       isInsured: true,
//       activities: [
//         {
//           activityName: 'CrossFit',
//           attendedLocation: 'Piscina Olímpica',
//           attendedDays: 'Lunes, miercoles y viernes 18:30',
//           goal: 'Cardio',
//           creationDate: new Date('2025-04-08'),
//           clientId: '30000012',
//         },
//       ],
//       healthData: {
//         clientId: '30000012',
//         healthInsurance: 'OSDE 410',
//         weight: 61,
//         height: 1.6,
//         currentStudies: '',
//         bloodPressure: '120/80',
//         diseases: '',
//         medications: '',
//         smoker: false,
//         studyImages: [],
//         boneIssues: '',
//       },
//     },
//     // ───────── Client 13
//     {
//       id: 'test',
//       name: 'Emilia',
//       lastName: 'Acosta',
//       dni: '30000013',
//       age: 19,
//       gender: 'F',
//       email: 'emilia.acosta@example.com',
//       phone: '+54 9 388 2001‑0013',
//       birthDate: new Date('2005-02-20'),
//       creationDate: new Date('2025-03-18'),
//       isActive: false,
//       photo: '/photos/emilia_acosta.jpg',
//       isInsured: false,
//       activities: [
//         {
//           activityName: 'Spinning',
//           attendedLocation: 'Sede Centro',
//           attendedDays: 'Lunes, miercoles y viernes 18:30',
//           goal: 'Hipertrofia',
//           creationDate: new Date('2025-03-18'),
//           clientId: '30000013',
//         },
//       ],
//       healthData: {
//         clientId: '30000013',
//         healthInsurance: '',
//         weight: 93,
//         height: 1.8,
//         currentStudies: '',
//         bloodPressure: '120/80',
//         diseases: '',
//         medications: '',
//         smoker: true,
//         studyImages: [],
//         boneIssues: '',
//       },
//     },
//     // ───────── Client 14
//     {
//       id: 'test',
//       name: 'Matías',
//       lastName: 'Gutiérrez',
//       dni: '30000014',
//       age: 35,
//       gender: 'M',
//       email: 'matias.gutierrez@example.com',
//       phone: '+54 9 235 2001‑0014',
//       birthDate: new Date('1989-04-15'),
//       creationDate: new Date('2025-04-22'),
//       isActive: true,
//       photo: '/photos/matias_gutierrez.jpg',
//       isInsured: true,
//       activities: [
//         {
//           activityName: 'Running',
//           attendedLocation: 'Piscina Olímpica',
//           attendedDays: 'Lunes, miercoles y viernes 18:30',
//           goal: 'Hipertrofia',
//           creationDate: new Date('2025-04-22'),
//           clientId: '30000014',
//         },
//       ],
//       healthData: {
//         clientId: '30000014',
//         healthInsurance: 'OSDE 210',
//         weight: 70,
//         height: 1.8,
//         currentStudies: '',
//         bloodPressure: '120/80',
//         diseases: '',
//         medications: '',
//         smoker: true,
//         studyImages: [],
//         boneIssues: '',
//       },
//     },
//     // ───────── Client 15
//     {
//       id: 'test',
//       name: 'Camila',
//       lastName: 'Sánchez',
//       dni: '30000015',
//       age: 34,
//       gender: 'F',
//       email: 'camila.sanchez@example.com',
//       phone: '+54 9 75 2001‑0015',
//       birthDate: new Date('1990-01-01'),
//       creationDate: new Date('2025-03-11'),
//       isActive: true,
//       photo: '/photos/camila_sanchez.jpg',
//       isInsured: false,
//       activities: [
//         {
//           activityName: 'Natación',
//           attendedLocation: 'Sede Oeste',
//           attendedDays: 'Lunes, miercoles y viernes 18:30',
//           goal: 'Fuerza',
//           creationDate: new Date('2025-03-11'),
//           clientId: '30000015',
//         },
//       ],
//       healthData: {
//         clientId: '30000015',
//         healthInsurance: '',
//         weight: 89,
//         height: 1.55,
//         currentStudies: '',
//         bloodPressure: '120/80',
//         diseases: '',
//         medications: '',
//         smoker: true,
//         studyImages: [],
//         boneIssues: '',
//       },
//     },
//     // ───────── Client 16
//     {
//       id: 'test',
//       name: 'Leandro',
//       lastName: 'Mendoza',
//       dni: '30000016',
//       age: 22,
//       gender: 'M',
//       email: 'leandro.mendoza@example.com',
//       phone: '+54 9 184 2001‑0016',
//       birthDate: new Date('2002-07-13'),
//       creationDate: new Date('2025-01-15'),
//       isActive: true,
//       photo: '/photos/leandro_mendoza.jpg',
//       isInsured: true,
//       activities: [
//         {
//           activityName: 'Spinning',
//           attendedLocation: 'Piscina Olímpica',
//           attendedDays: 'Lunes, miercoles y viernes 18:30',
//           goal: 'Cardio',
//           creationDate: new Date('2025-01-15'),
//           clientId: '30000016',
//         },
//       ],
//       healthData: {
//         clientId: '30000016',
//         healthInsurance: 'Sancor Salud',
//         weight: 79,
//         height: 1.63,
//         currentStudies: '',
//         bloodPressure: '120/80',
//         diseases: '',
//         medications: '',
//         smoker: false,
//         studyImages: [],
//         boneIssues: '',
//       },
//     },
//     // ───────── Client 17
//     {
//       id: 'test',
//       name: 'Paula',
//       lastName: 'Alvarez',
//       dni: '30000017',
//       age: 33,
//       gender: 'F',
//       email: 'paula.alvarez@example.com',
//       phone: '+54 9 33 2001‑0017',
//       birthDate: new Date('1991-02-01'),
//       creationDate: new Date('2025-02-17'),
//       isActive: false,
//       photo: '/photos/paula_alvarez.jpg',
//       isInsured: true,
//       activities: [
//         {
//           activityName: 'Natación',
//           attendedLocation: 'Piscina Olímpica',
//           attendedDays: 'Lunes, miercoles y viernes 18:30',
//           goal: 'Diversión',
//           creationDate: new Date('2025-02-17'),
//           clientId: '30000017',
//         },
//       ],
//       healthData: {
//         clientId: '30000017',
//         healthInsurance: 'OSDE 210',
//         weight: 85,
//         height: 1.7,
//         currentStudies: '',
//         bloodPressure: '120/80',
//         diseases: '',
//         medications: '',
//         smoker: false,
//         studyImages: [],
//         boneIssues: '',
//       },
//     },
//     // ───────── Client 18
//     {
//       id: 'test',
//       name: 'Ramiro',
//       lastName: 'Domínguez',
//       dni: '30000018',
//       age: 36,
//       gender: 'M',
//       email: 'ramiro.dominguez@example.com',
//       phone: '+54 9 128 2001‑0018',
//       birthDate: new Date('1988-09-10'),
//       creationDate: new Date('2025-04-07'),
//       isActive: false,
//       photo: '/photos/ramiro_dominguez.jpg',
//       isInsured: true,
//       activities: [
//         {
//           activityName: 'Calistenia',
//           attendedLocation: 'Piscina Olímpica',
//           attendedDays: 'Lunes, miercoles y viernes 18:30',
//           goal: 'Cardio',
//           creationDate: new Date('2025-04-07'),
//           clientId: '30000018',
//         },
//       ],
//       healthData: {
//         clientId: '30000018',
//         healthInsurance: 'Swiss Medical',
//         weight: 67,
//         height: 1.58,
//         currentStudies: '',
//         bloodPressure: '120/80',
//         diseases: '',
//         medications: '',
//         smoker: true,
//         studyImages: [],
//         boneIssues: '',
//       },
//     },
//     // ───────── Client 19
//     {
//       id: 'test',
//       name: 'Micaela',
//       lastName: 'Cabrera',
//       dni: '30000019',
//       age: 24,
//       gender: 'F',
//       email: 'micaela.cabrera@example.com',
//       phone: '+54 9 209 2001‑0019',
//       birthDate: new Date('2000-10-12'),
//       creationDate: new Date('2025-03-24'),
//       isActive: true,
//       photo: '/photos/micaela_cabrera.jpg',
//       isInsured: true,
//       activities: [
//         {
//           activityName: 'Natación',
//           attendedLocation: 'Sede Norte',
//           attendedDays: 'Lunes, miercoles y viernes 18:30',
//           goal: 'Hipertrofia',
//           creationDate: new Date('2025-03-24'),
//           clientId: '30000019',
//         },
//       ],
//       healthData: {
//         clientId: '30000019',
//         healthInsurance: 'OSDE 210',
//         weight: 83,
//         height: 1.82,
//         currentStudies: '',
//         bloodPressure: '120/80',
//         diseases: '',
//         medications: '',
//         smoker: true,
//         studyImages: [],
//         boneIssues: '',
//       },
//     },
//     // ───────── Client 20
//     {
//       id: 'test',
//       name: 'Sebastián',
//       lastName: 'Vera',
//       dni: '30000020',
//       age: 42,
//       gender: 'M',
//       email: 'sebastian.vera@example.com',
//       phone: '+54 9 25 2001‑0020',
//       birthDate: new Date('1982-06-27'),
//       creationDate: new Date('2025-02-02'),
//       isActive: false,
//       photo: '/photos/sebastian_vera.jpg',
//       isInsured: false,
//       activities: [
//         {
//           activityName: 'Boxeo',
//           attendedLocation: 'Plaza Abierta',
//           attendedDays: 'Lunes, miercoles y viernes 18:30',
//           goal: 'Hipertrofia',
//           creationDate: new Date('2025-02-02'),
//           clientId: '30000020',
//         },
//       ],
//       healthData: {
//         clientId: '30000020',
//         healthInsurance: '',
//         weight: 61,
//         height: 1.6,
//         currentStudies: '',
//         bloodPressure: '120/80',
//         diseases: '',
//         medications: '',
//         smoker: true,
//         studyImages: [],
//         boneIssues: '',
//       },
//     },
//     // ───────── Client 21
//     {
//       id: 'test',
//       name: 'Antonella',
//       lastName: 'López',
//       dni: '30000021',
//       age: 37,
//       gender: 'F',
//       email: 'antonella.lopez@example.com',
//       phone: '+54 9 208 2001‑0021',
//       birthDate: new Date('1987-12-26'),
//       creationDate: new Date('2025-02-19'),
//       isActive: false,
//       photo: '/photos/antonella_lopez.jpg',
//       isInsured: true,
//       activities: [
//         {
//           activityName: 'Yoga',
//           attendedLocation: 'Piscina Olímpica',
//           attendedDays: 'Lunes, miercoles y viernes 18:30',
//           goal: 'Triatlón',
//           creationDate: new Date('2025-02-19'),
//           clientId: '30000021',
//         },
//       ],
//       healthData: {
//         clientId: '30000021',
//         healthInsurance: 'OSDE 410',
//         weight: 93,
//         height: 1.67,
//         currentStudies: '',
//         bloodPressure: '120/80',
//         diseases: '',
//         medications: '',
//         smoker: false,
//         studyImages: [],
//         boneIssues: '',
//       },
//     },
//     // ───────── Client 22
//     {
//       id: 'test',
//       name: 'Julián',
//       lastName: 'Castro',
//       dni: '30000022',
//       age: 30,
//       gender: 'M',
//       email: 'julian.castro@example.com',
//       phone: '+54 9 259 2001‑0022',
//       birthDate: new Date('1994-04-13'),
//       creationDate: new Date('2025-04-10'),
//       isActive: false,
//       photo: '/photos/julian_castro.jpg',
//       isInsured: false,
//       activities: [
//         {
//           activityName: 'Calistenia',
//           attendedLocation: 'Parque Independencia',
//           attendedDays: 'Lunes, miercoles y viernes 18:30',
//           goal: 'Hipertrofia',
//           creationDate: new Date('2025-04-10'),
//           clientId: '30000022',
//         },
//       ],
//       healthData: {
//         clientId: '30000022',
//         healthInsurance: '',
//         weight: 58,
//         height: 1.85,
//         currentStudies: '',
//         bloodPressure: '120/80',
//         diseases: '',
//         medications: '',
//         smoker: true,
//         studyImages: [],
//         boneIssues: '',
//       },
//     },
//     // ───────── Client 23
//     {
//       id: 'test',
//       name: 'Florencia',
//       lastName: 'Molina',
//       dni: '30000023',
//       age: 23,
//       gender: 'F',
//       email: 'florencia.molina@example.com',
//       phone: '+54 9 89 2001‑0023',
//       birthDate: new Date('2001-07-20'),
//       creationDate: new Date('2025-03-08'),
//       isActive: false,
//       photo: '/photos/florencia_molina.jpg',
//       isInsured: true,
//       activities: [
//         {
//           activityName: 'Spinning',
//           attendedLocation: 'Parque Independencia',
//           attendedDays: 'Lunes, miercoles y viernes 18:30',
//           goal: 'Fuerza',
//           creationDate: new Date('2025-03-08'),
//           clientId: '30000023',
//         },
//       ],
//       healthData: {
//         clientId: '30000023',
//         healthInsurance: 'OSDE 210',
//         weight: 83,
//         height: 1.73,
//         currentStudies: '',
//         bloodPressure: '120/80',
//         diseases: '',
//         medications: '',
//         smoker: false,
//         studyImages: [],
//         boneIssues: '',
//       },
//     },
//     // ───────── Client 24
//     {
//       id: 'test',
//       name: 'Facundo',
//       lastName: 'Peralta',
//       dni: '30000024',
//       age: 26,
//       gender: 'M',
//       email: 'facundo.peralta@example.com',
//       phone: '+54 9 119 2001‑0024',
//       birthDate: new Date('1998-05-14'),
//       creationDate: new Date('2025-01-18'),
//       isActive: true,
//       photo: '/photos/facundo_peralta.jpg',
//       isInsured: true,
//       activities: [
//         {
//           activityName: 'Running',
//           attendedLocation: 'Sede Centro',
//           attendedDays: 'Lunes, miercoles y viernes 18:30',
//           goal: 'Cardio',
//           creationDate: new Date('2025-01-18'),
//           clientId: '30000024',
//         },
//       ],
//       healthData: {
//         clientId: '30000024',
//         healthInsurance: 'Medifé',
//         weight: 56,
//         height: 1.66,
//         currentStudies: '',
//         bloodPressure: '120/80',
//         diseases: '',
//         medications: '',
//         smoker: false,
//         studyImages: [],
//         boneIssues: '',
//       },
//     },
//     // ───────── Client 25
//     {
//       id: 'test',
//       name: 'Carolina',
//       lastName: 'Rojas',
//       dni: '30000025',
//       age: 38,
//       gender: 'F',
//       email: 'carolina.rojas@example.com',
//       phone: '+54 9 123 2001‑0025',
//       birthDate: new Date('1986-02-10'),
//       creationDate: new Date('2025-01-20'),
//       isActive: true,
//       photo: '/photos/carolina_rojas.jpg',
//       isInsured: true,
//       activities: [
//         {
//           activityName: 'Calistenia',
//           attendedLocation: 'Sede Norte',
//           attendedDays: 'Lunes, miercoles y viernes 18:30',
//           goal: 'Triatlón',
//           creationDate: new Date('2025-01-20'),
//           clientId: '30000025',
//         },
//       ],
//       healthData: {
//         clientId: '30000025',
//         healthInsurance: 'OSDE 410',
//         weight: 61,
//         height: 1.63,
//         currentStudies: '',
//         bloodPressure: '120/80',
//         diseases: '',
//         medications: '',
//         smoker: true,
//         studyImages: [],
//         boneIssues: '',
//       },
//     },
//     // ───────── Client 26
//     {
//       id: 'test',
//       name: 'Ignacio',
//       lastName: 'Herrera',
//       dni: '30000026',
//       age: 19,
//       gender: 'M',
//       email: 'ignacio.herrera@example.com',
//       phone: '+54 9 226 2001‑0026',
//       birthDate: new Date('2005-01-25'),
//       creationDate: new Date('2025-02-01'),
//       isActive: false,
//       photo: '/photos/ignacio_herrera.jpg',
//       isInsured: false,
//       activities: [
//         {
//           activityName: 'Funcional',
//           attendedLocation: 'Sede Oeste',
//           attendedDays: 'Lunes, miercoles y viernes 18:30',
//           goal: 'Triatlón',
//           creationDate: new Date('2025-02-01'),
//           clientId: '30000026',
//         },
//       ],
//       healthData: {
//         clientId: '30000026',
//         healthInsurance: '',
//         weight: 66,
//         height: 1.84,
//         currentStudies: '',
//         bloodPressure: '120/80',
//         diseases: '',
//         medications: '',
//         smoker: false,
//         studyImages: [],
//         boneIssues: '',
//       },
//     },
//     // ───────── Client 27
//     {
//       id: 'test',
//       name: 'Melina',
//       lastName: 'Vázquez',
//       dni: '30000027',
//       age: 40,
//       gender: 'F',
//       email: 'melina.vazquez@example.com',
//       phone: '+54 9 189 2001‑0027',
//       birthDate: new Date('1984-07-18'),
//       creationDate: new Date('2025-04-09'),
//       isActive: false,
//       photo: '/photos/melina_vazquez.jpg',
//       isInsured: true,
//       activities: [
//         {
//           activityName: 'Funcional',
//           attendedLocation: 'Parque Independencia',
//           attendedDays: 'Lunes, miercoles y viernes 18:30',
//           goal: 'Dominadas',
//           creationDate: new Date('2025-04-09'),
//           clientId: '30000027',
//         },
//       ],
//       healthData: {
//         clientId: '30000027',
//         healthInsurance: 'Galeno',
//         weight: 92,
//         height: 1.7,
//         currentStudies: '',
//         bloodPressure: '120/80',
//         diseases: '',
//         medications: '',
//         smoker: true,
//         studyImages: [],
//         boneIssues: '',
//       },
//     },
//     // ───────── Client 28
//     {
//       id: 'test',
//       name: 'Bruno',
//       lastName: 'Navarro',
//       dni: '30000028',
//       age: 41,
//       gender: 'M',
//       email: 'bruno.navarro@example.com',
//       phone: '+54 9 92 2001‑0028',
//       birthDate: new Date('1983-10-18'),
//       creationDate: new Date('2025-03-20'),
//       isActive: true,
//       photo: '/photos/bruno_navarro.jpg',
//       isInsured: false,
//       activities: [
//         {
//           activityName: 'Boxeo',
//           attendedLocation: 'Sede Centro',
//           attendedDays: 'Lunes, miercoles y viernes 18:30',
//           goal: 'Dominadas',
//           creationDate: new Date('2025-03-20'),
//           clientId: '30000028',
//         },
//       ],
//       healthData: {
//         clientId: '30000028',
//         healthInsurance: '',
//         weight: 79,
//         height: 1.7,
//         currentStudies: '',
//         bloodPressure: '120/80',
//         diseases: '',
//         medications: '',
//         smoker: true,
//         studyImages: [],
//         boneIssues: '',
//       },
//     },
//   ],
//   [
//     // ───────── Client 29
//     {
//       id: 'test',
//       name: 'Rocío',
//       lastName: 'Ortega',
//       dni: '30000029',
//       age: 22,
//       gender: 'F',
//       email: 'rocio.ortega@example.com',
//       phone: '+54 9 156 2001‑0029',
//       birthDate: new Date('2002-10-22'),
//       creationDate: new Date('2025-03-05'),
//       isActive: true,
//       photo: '/photos/rocio_ortega.jpg',
//       isInsured: true,
//       activities: [
//         {
//           activityName: 'Funcional',
//           attendedLocation: 'Piscina Olímpica',
//           attendedDays: 'Lunes, miercoles y viernes 18:30',
//           goal: 'Fuerza',
//           creationDate: new Date('2025-03-05'),
//           clientId: '30000029',
//         },
//       ],
//       healthData: {
//         clientId: '30000029',
//         healthInsurance: 'Galeno',
//         weight: 60,
//         height: 1.71,
//         currentStudies: '',
//         bloodPressure: '120/80',
//         diseases: '',
//         medications: '',
//         smoker: false,
//         studyImages: [],
//         boneIssues: '',
//       },
//     },
//     // ───────── Client 30
//     {
//       id: 'test',
//       name: 'Franco',
//       lastName: 'Figueroa',
//       dni: '30000030',
//       age: 35,
//       gender: 'M',
//       email: 'franco.figueroa@example.com',
//       phone: '+54 9 163 2001‑0030',
//       birthDate: new Date('1989-08-18'),
//       creationDate: new Date('2025-03-24'),
//       isActive: true,
//       photo: '/photos/franco_figueroa.jpg',
//       isInsured: false,
//       activities: [
//         {
//           activityName: 'Funcional',
//           attendedLocation: 'Sede Sur',
//           attendedDays: 'Lunes, miercoles y viernes 18:30',
//           goal: 'Triatlón',
//           creationDate: new Date('2025-03-24'),
//           clientId: '30000030',
//         },
//       ],
//       healthData: {
//         clientId: '30000030',
//         healthInsurance: '',
//         weight: 93,
//         height: 1.6,
//         currentStudies: '',
//         bloodPressure: '120/80',
//         diseases: '',
//         medications: '',
//         smoker: false,
//         studyImages: [],
//         boneIssues: '',
//       },
//     },
//     // ───────── Client 31
//     {
//       id: 'test',
//       name: 'Lautaro',
//       lastName: 'Correa',
//       dni: '30000031',
//       age: 18,
//       gender: 'M',
//       email: 'lautaro.correa@example.com',
//       phone: '+54 9 358 2001‑0031',
//       birthDate: new Date('2005-11-14'),
//       creationDate: new Date('2025-02-28'),
//       isActive: false,
//       photo: '/photos/lautaro_correa.jpg',
//       isInsured: false,
//       activities: [
//         {
//           activityName: 'Pilates',
//           attendedLocation: 'Parque Independencia',
//           attendedDays: 'Lunes, miercoles y viernes 18:30',
//           goal: 'Cardio',
//           creationDate: new Date('2025-02-28'),
//           clientId: '30000031',
//         },
//       ],
//       healthData: {
//         clientId: '30000031',
//         healthInsurance: '',
//         weight: 87,
//         height: 1.57,
//         currentStudies: '',
//         bloodPressure: '120/80',
//         diseases: '',
//         medications: '',
//         smoker: false,
//         studyImages: [],
//         boneIssues: '',
//       },
//     },
//     // ───────── Client 32
//     {
//       id: 'test',
//       name: 'Noelia',
//       lastName: 'Ponce',
//       dni: '30000032',
//       age: 38,
//       gender: 'F',
//       email: 'noelia.ponce@example.com',
//       phone: '+54 9 153 2001‑0032',
//       birthDate: new Date('1986-02-27'),
//       creationDate: new Date('2025-01-13'),
//       isActive: true,
//       photo: '/photos/noelia_ponce.jpg',
//       isInsured: true,
//       activities: [
//         {
//           activityName: 'Calistenia',
//           attendedLocation: 'Sede Centro',
//           attendedDays: 'Lunes, miercoles y viernes 18:30',
//           goal: 'Fuerza',
//           creationDate: new Date('2025-01-13'),
//           clientId: '30000032',
//         },
//       ],
//       healthData: {
//         clientId: '30000032',
//         healthInsurance: 'OSDE 410',
//         weight: 56,
//         height: 1.9,
//         currentStudies: '',
//         bloodPressure: '120/80',
//         diseases: '',
//         medications: '',
//         smoker: false,
//         studyImages: [],
//         boneIssues: '',
//       },
//     },
//     // ───────── Client 33
//     {
//       id: 'test',
//       name: 'Pablo',
//       lastName: 'Giménez',
//       dni: '30000033',
//       age: 24,
//       gender: 'M',
//       email: 'pablo.gimenez@example.com',
//       phone: '+54 9 142 2001‑0033',
//       birthDate: new Date('2000-04-13'),
//       creationDate: new Date('2025-03-05'),
//       isActive: true,
//       photo: '/photos/pablo_gimenez.jpg',
//       isInsured: false,
//       activities: [
//         {
//           activityName: 'Spinning',
//           attendedLocation: 'Parque Independencia',
//           attendedDays: 'Lunes, miercoles y viernes 18:30',
//           goal: 'Cardio',
//           creationDate: new Date('2025-03-05'),
//           clientId: '30000033',
//         },
//       ],
//       healthData: {
//         clientId: '30000033',
//         healthInsurance: '',
//         weight: 85,
//         height: 1.73,
//         currentStudies: '',
//         bloodPressure: '120/80',
//         diseases: '',
//         medications: '',
//         smoker: true,
//         studyImages: [],
//         boneIssues: '',
//       },
//     },
//     // ───────── Client 34
//     {
//       id: 'test',
//       name: 'Ailén',
//       lastName: 'Rivera',
//       dni: '30000034',
//       age: 29,
//       gender: 'F',
//       email: 'ailen.rivera@example.com',
//       phone: '+54 9 140 2001‑0034',
//       birthDate: new Date('1995-03-21'),
//       creationDate: new Date('2025-02-25'),
//       isActive: false,
//       photo: '/photos/ailen_rivera.jpg',
//       isInsured: true,
//       activities: [
//         {
//           activityName: 'Running',
//           attendedLocation: 'Piscina Olímpica',
//           attendedDays: 'Lunes, miercoles y viernes 18:30',
//           goal: 'Hipertrofia',
//           creationDate: new Date('2025-02-25'),
//           clientId: '30000034',
//         },
//       ],
//       healthData: {
//         clientId: '30000034',
//         healthInsurance: 'OSDE 210',
//         weight: 58,
//         height: 1.63,
//         currentStudies: '',
//         bloodPressure: '120/80',
//         diseases: '',
//         medications: '',
//         smoker: true,
//         studyImages: [],
//         boneIssues: '',
//       },
//     },
//     // ───────── Client 35
//     {
//       id: 'test',
//       name: 'Esteban',
//       lastName: 'Salas',
//       dni: '30000035',
//       age: 21,
//       gender: 'M',
//       email: 'esteban.salas@example.com',
//       phone: '+54 9 358 2001‑0035',
//       birthDate: new Date('2003-09-14'),
//       creationDate: new Date('2025-03-12'),
//       isActive: true,
//       photo: '/photos/esteban_salas.jpg',
//       isInsured: true,
//       activities: [
//         {
//           activityName: 'Yoga',
//           attendedLocation: 'Parque Independencia',
//           attendedDays: 'Lunes, miercoles y viernes 18:30',
//           goal: 'Cardio',
//           creationDate: new Date('2025-03-12'),
//           clientId: '30000035',
//         },
//       ],
//       healthData: {
//         clientId: '30000035',
//         healthInsurance: 'Medifé',
//         weight: 70,
//         height: 1.89,
//         currentStudies: '',
//         bloodPressure: '120/80',
//         diseases: '',
//         medications: '',
//         smoker: false,
//         studyImages: [],
//         boneIssues: '',
//       },
//     },
//     // ───────── Client 36
//     {
//       id: 'test',
//       name: 'Milagros',
//       lastName: 'Ferreyra',
//       dni: '30000036',
//       age: 36,
//       gender: 'F',
//       email: 'milagros.ferreyra@example.com',
//       phone: '+54 9 53 2001‑0036',
//       birthDate: new Date('1988-07-25'),
//       creationDate: new Date('2025-02-18'),
//       isActive: true,
//       photo: '/photos/milagros_ferreyra.jpg',
//       isInsured: true,
//       activities: [
//         {
//           activityName: 'Pilates',
//           attendedLocation: 'Parque Independencia',
//           attendedDays: 'Lunes, miercoles y viernes 18:30',
//           goal: 'Diversión',
//           creationDate: new Date('2025-02-18'),
//           clientId: '30000036',
//         },
//       ],
//       healthData: {
//         clientId: '30000036',
//         healthInsurance: 'Swiss Medical',
//         weight: 85,
//         height: 1.57,
//         currentStudies: '',
//         bloodPressure: '120/80',
//         diseases: '',
//         medications: '',
//         smoker: true,
//         studyImages: [],
//         boneIssues: '',
//       },
//     },
//     // ───────── Client 37
//     {
//       id: 'test',
//       name: 'Cristian',
//       lastName: 'Campos',
//       dni: '30000037',
//       age: 21,
//       gender: 'M',
//       email: 'cristian.campos@example.com',
//       phone: '+54 9 55 2001‑0037',
//       birthDate: new Date('2003-11-23'),
//       creationDate: new Date('2025-04-23'),
//       isActive: false,
//       photo: '/photos/cristian_campos.jpg',
//       isInsured: true,
//       activities: [
//         {
//           activityName: 'Natación',
//           attendedLocation: 'Plaza Abierta',
//           attendedDays: 'Lunes, miercoles y viernes 18:30',
//           goal: 'Diversión',
//           creationDate: new Date('2025-04-23'),
//           clientId: '30000037',
//         },
//       ],
//       healthData: {
//         clientId: '30000037',
//         healthInsurance: 'OSDE 410',
//         weight: 70,
//         height: 1.86,
//         currentStudies: '',
//         bloodPressure: '120/80',
//         diseases: '',
//         medications: '',
//         smoker: false,
//         studyImages: [],
//         boneIssues: '',
//       },
//     },
//     // ───────── Client 38
//     {
//       id: 'test',
//       name: 'Daniela',
//       lastName: 'Carrizo',
//       dni: '30000038',
//       age: 19,
//       gender: 'F',
//       email: 'daniela.carrizo@example.com',
//       phone: '+54 9 75 2001‑0038',
//       birthDate: new Date('2005-11-23'),
//       creationDate: new Date('2025-02-10'),
//       isActive: true,
//       photo: '/photos/daniela_carrizo.jpg',
//       isInsured: false,
//       activities: [
//         {
//           activityName: 'Running',
//           attendedLocation: 'Sede Norte',
//           attendedDays: 'Lunes, miercoles y viernes 18:30',
//           goal: 'Dominadas',
//           creationDate: new Date('2025-02-10'),
//           clientId: '30000038',
//         },
//       ],
//       healthData: {
//         clientId: '30000038',
//         healthInsurance: '',
//         weight: 93,
//         height: 1.88,
//         currentStudies: '',
//         bloodPressure: '120/80',
//         diseases: '',
//         medications: '',
//         smoker: false,
//         studyImages: [],
//         boneIssues: '',
//       },
//     },
//     // ───────── Client 39
//     {
//       id: 'test',
//       name: 'Hernán',
//       lastName: 'Barrios',
//       dni: '30000039',
//       age: 34,
//       gender: 'M',
//       email: 'hernan.barrios@example.com',
//       phone: '+54 9 304 2001‑0039',
//       birthDate: new Date('1990-09-18'),
//       creationDate: new Date('2025-03-07'),
//       isActive: false,
//       photo: '/photos/hernan_barrios.jpg',
//       isInsured: true,
//       activities: [
//         {
//           activityName: 'Running',
//           attendedLocation: 'Sede Centro',
//           attendedDays: 'Lunes, miercoles y viernes 18:30',
//           goal: 'Diversión',
//           creationDate: new Date('2025-03-07'),
//           clientId: '30000039',
//         },
//       ],
//       healthData: {
//         clientId: '30000039',
//         healthInsurance: 'OSDE 210',
//         weight: 78,
//         height: 1.83,
//         currentStudies: '',
//         bloodPressure: '120/80',
//         diseases: '',
//         medications: '',
//         smoker: false,
//         studyImages: [],
//         boneIssues: '',
//       },
//     },
//     // ───────── Client 40
//     {
//       id: 'test',
//       name: 'Belén',
//       lastName: 'Suárez',
//       dni: '30000040',
//       age: 26,
//       gender: 'F',
//       email: 'belen.suarez@example.com',
//       phone: '+54 9 50 2001‑0040',
//       birthDate: new Date('1998-02-15'),
//       creationDate: new Date('2025-03-14'),
//       isActive: true,
//       photo: '/photos/belen_suarez.jpg',
//       isInsured: false,
//       activities: [
//         {
//           activityName: 'Spinning',
//           attendedLocation: 'Parque Independencia',
//           attendedDays: 'Lunes, miercoles y viernes 18:30',
//           goal: 'Diversión',
//           creationDate: new Date('2025-03-14'),
//           clientId: '30000040',
//         },
//       ],
//       healthData: {
//         clientId: '30000040',
//         healthInsurance: '',
//         weight: 78,
//         height: 1.85,
//         currentStudies: '',
//         bloodPressure: '120/80',
//         diseases: '',
//         medications: '',
//         smoker: true,
//         studyImages: [],
//         boneIssues: '',
//       },
//     },
//     // ───────── Client 41
//     {
//       id: 'test',
//       name: 'Germán',
//       lastName: 'Aguilar',
//       dni: '30000041',
//       age: 40,
//       gender: 'M',
//       email: 'german.aguilar@example.com',
//       phone: '+54 9 57 2001‑0041',
//       birthDate: new Date('1984-10-13'),
//       creationDate: new Date('2025-02-13'),
//       isActive: false,
//       photo: '/photos/german_aguilar.jpg',
//       isInsured: true,
//       activities: [
//         {
//           activityName: 'Natación',
//           attendedLocation: 'Sede Norte',
//           attendedDays: 'Lunes, miercoles y viernes 18:30',
//           goal: 'Cardio',
//           creationDate: new Date('2025-02-13'),
//           clientId: '30000041',
//         },
//       ],
//       healthData: {
//         clientId: '30000041',
//         healthInsurance: 'OSDE 410',
//         weight: 72,
//         height: 1.89,
//         currentStudies: '',
//         bloodPressure: '120/80',
//         diseases: '',
//         medications: '',
//         smoker: false,
//         studyImages: [],
//         boneIssues: '',
//       },
//     },
//     // ───────── Client 42
//     {
//       id: 'test',
//       name: 'Luciana',
//       lastName: 'Cardozo',
//       dni: '30000042',
//       age: 25,
//       gender: 'F',
//       email: 'luciana.cardozo@example.com',
//       phone: '+54 9 119 2001‑0042',
//       birthDate: new Date('1999-10-19'),
//       creationDate: new Date('2025-04-21'),
//       isActive: true,
//       photo: '/photos/luciana_cardozo.jpg',
//       isInsured: false,
//       activities: [
//         {
//           activityName: 'Funcional',
//           attendedLocation: 'Plaza Abierta',
//           attendedDays: 'Lunes, miercoles y viernes 18:30',
//           goal: 'Hipertrofia',
//           creationDate: new Date('2025-04-21'),
//           clientId: '30000042',
//         },
//       ],
//       healthData: {
//         clientId: '30000042',
//         healthInsurance: '',
//         weight: 71,
//         height: 1.73,
//         currentStudies: '',
//         bloodPressure: '120/80',
//         diseases: '',
//         medications: '',
//         smoker: true,
//         studyImages: [],
//         boneIssues: '',
//       },
//     },
//     // ───────── Client 43
//     {
//       id: 'test',
//       name: 'Mauricio',
//       lastName: 'Chávez',
//       dni: '30000043',
//       age: 20,
//       gender: 'M',
//       email: 'mauricio.chavez@example.com',
//       phone: '+54 9 346 2001‑0043',
//       birthDate: new Date('2004-03-20'),
//       creationDate: new Date('2025-04-10'),
//       isActive: false,
//       photo: '/photos/mauricio_chavez.jpg',
//       isInsured: false,
//       activities: [
//         {
//           activityName: 'Yoga',
//           attendedLocation: 'Sede Sur',
//           attendedDays: 'Lunes, miercoles y viernes 18:30',
//           goal: 'Diversión',
//           creationDate: new Date('2025-04-10'),
//           clientId: '30000043',
//         },
//       ],
//       healthData: {
//         clientId: '30000043',
//         healthInsurance: '',
//         weight: 65,
//         height: 1.77,
//         currentStudies: '',
//         bloodPressure: '120/80',
//         diseases: '',
//         medications: '',
//         smoker: false,
//         studyImages: [],
//         boneIssues: '',
//       },
//     },
//     // ───────── Client 44
//     {
//       id: 'test',
//       name: 'Cecilia',
//       lastName: 'Delgado',
//       dni: '30000044',
//       age: 34,
//       gender: 'F',
//       email: 'cecilia.delgado@example.com',
//       phone: '+54 9 161 2001‑0044',
//       birthDate: new Date('1990-03-18'),
//       creationDate: new Date('2025-03-10'),
//       isActive: false,
//       photo: '/photos/cecilia_delgado.jpg',
//       isInsured: true,
//       activities: [
//         {
//           activityName: 'Pilates',
//           attendedLocation: 'Sede Oeste',
//           attendedDays: 'Lunes, miercoles y viernes 18:30',
//           goal: 'Triatlón',
//           creationDate: new Date('2025-03-10'),
//           clientId: '30000044',
//         },
//       ],
//       healthData: {
//         clientId: '30000044',
//         healthInsurance: 'Galeno',
//         weight: 90,
//         height: 1.55,
//         currentStudies: '',
//         bloodPressure: '120/80',
//         diseases: '',
//         medications: '',
//         smoker: false,
//         studyImages: [],
//         boneIssues: '',
//       },
//     },
//     // ───────── Client 45
//     {
//       id: 'test',
//       name: 'Rodrigo',
//       lastName: 'Escobar',
//       dni: '30000045',
//       age: 19,
//       gender: 'M',
//       email: 'rodrigo.escobar@example.com',
//       phone: '+54 9 86 2001‑0045',
//       birthDate: new Date('2005-03-08'),
//       creationDate: new Date('2025-02-24'),
//       isActive: true,
//       photo: '/photos/rodrigo_escobar.jpg',
//       isInsured: false,
//       activities: [
//         {
//           activityName: 'Funcional',
//           attendedLocation: 'Parque Independencia',
//           attendedDays: 'Lunes, miercoles y viernes 18:30',
//           goal: 'Fuerza',
//           creationDate: new Date('2025-02-24'),
//           clientId: '30000045',
//         },
//       ],
//       healthData: {
//         clientId: '30000045',
//         healthInsurance: '',
//         weight: 92,
//         height: 1.72,
//         currentStudies: '',
//         bloodPressure: '120/80',
//         diseases: '',
//         medications: '',
//         smoker: true,
//         studyImages: [],
//         boneIssues: '',
//       },
//     },
//     // ───────── Client 46
//     {
//       id: 'test',
//       name: 'Yanina',
//       lastName: 'Frías',
//       dni: '30000046',
//       age: 40,
//       gender: 'F',
//       email: 'yanina.frias@example.com',
//       phone: '+54 9 56 2001‑0046',
//       birthDate: new Date('1984-02-24'),
//       creationDate: new Date('2025-01-29'),
//       isActive: false,
//       photo: '/photos/yanina_frias.jpg',
//       isInsured: true,
//       activities: [
//         {
//           activityName: 'Running',
//           attendedLocation: 'Sede Norte',
//           attendedDays: 'Lunes, miercoles y viernes 18:30',
//           goal: 'Hipertrofia',
//           creationDate: new Date('2025-01-29'),
//           clientId: '30000046',
//         },
//       ],
//       healthData: {
//         clientId: '30000046',
//         healthInsurance: 'OSDE 410',
//         weight: 93,
//         height: 1.87,
//         currentStudies: '',
//         bloodPressure: '120/80',
//         diseases: '',
//         medications: '',
//         smoker: true,
//         studyImages: [],
//         boneIssues: '',
//       },
//     },
//     // ───────── Client 47
//     {
//       id: 'test',
//       name: 'Adrián',
//       lastName: 'Godoy',
//       dni: '30000047',
//       age: 35,
//       gender: 'M',
//       email: 'adrian.godoy@example.com',
//       phone: '+54 9 373 2001‑0047',
//       birthDate: new Date('1989-10-22'),
//       creationDate: new Date('2025-03-01'),
//       isActive: true,
//       photo: '/photos/adrian_godoy.jpg',
//       isInsured: true,
//       activities: [
//         {
//           activityName: 'Yoga',
//           attendedLocation: 'Sede Centro',
//           attendedDays: 'Lunes, miercoles y viernes 18:30',
//           goal: 'Diversión',
//           creationDate: new Date('2025-03-01'),
//           clientId: '30000047',
//         },
//       ],
//       healthData: {
//         clientId: '30000047',
//         healthInsurance: 'Medifé',
//         weight: 85,
//         height: 1.77,
//         currentStudies: '',
//         bloodPressure: '120/80',
//         diseases: '',
//         medications: '',
//         smoker: false,
//         studyImages: [],
//         boneIssues: '',
//       },
//     },
//     // ───────── Client 48
//     {
//       id: 'test',
//       name: 'Mariana',
//       lastName: 'Insúa',
//       dni: '30000048',
//       age: 26,
//       gender: 'F',
//       email: 'mariana.insua@example.com',
//       phone: '+54 9 193 2001‑0048',
//       birthDate: new Date('1998-10-17'),
//       creationDate: new Date('2025-02-06'),
//       isActive: false,
//       photo: '/photos/mariana_insua.jpg',
//       isInsured: false,
//       activities: [
//         {
//           activityName: 'Boxeo',
//           attendedLocation: 'Plaza Abierta',
//           attendedDays: 'Lunes, miercoles y viernes 18:30',
//           goal: 'Diversión',
//           creationDate: new Date('2025-02-06'),
//           clientId: '30000048',
//         },
//       ],
//       healthData: {
//         clientId: '30000048',
//         healthInsurance: '',
//         weight: 78,
//         height: 1.74,
//         currentStudies: '',
//         bloodPressure: '120/80',
//         diseases: '',
//         medications: '',
//         smoker: false,
//         studyImages: [],
//         boneIssues: '',
//       },
//     },
//     // ───────── Client 49
//     {
//       id: 'test',
//       name: 'Ezequiel',
//       lastName: 'Jara',
//       dni: '30000049',
//       age: 24,
//       gender: 'M',
//       email: 'ezequiel.jara@example.com',
//       phone: '+54 9 89 2001‑0049',
//       birthDate: new Date('2000-07-20'),
//       creationDate: new Date('2025-04-08'),
//       isActive: true,
//       photo: '/photos/ezequiel_jara.jpg',
//       isInsured: false,
//       activities: [
//         {
//           activityName: 'Musculación',
//           attendedLocation: 'Parque Independencia',
//           attendedDays: 'Lunes, miercoles y viernes 18:30',
//           goal: 'Hipertrofia',
//           creationDate: new Date('2025-04-08'),
//           clientId: '30000049',
//         },
//       ],
//       healthData: {
//         clientId: '30000049',
//         healthInsurance: '',
//         weight: 80,
//         height: 1.66,
//         currentStudies: '',
//         bloodPressure: '120/80',
//         diseases: '',
//         medications: '',
//         smoker: true,
//         studyImages: [],
//         boneIssues: '',
//       },
//     },
//     // ───────── Client 50
//     {
//       id: 'test',
//       name: 'Natalia',
//       lastName: 'Krause',
//       dni: '30000050',
//       age: 30,
//       gender: 'F',
//       email: 'natalia.krause@example.com',
//       phone: '+54 9 225 2001‑0050',
//       birthDate: new Date('1994-04-13'),
//       creationDate: new Date('2025-02-21'),
//       isActive: true,
//       photo: '/photos/natalia_krause.jpg',
//       isInsured: true,
//       activities: [
//         {
//           activityName: 'Running',
//           attendedLocation: 'Plaza Abierta',
//           attendedDays: 'Lunes, miercoles y viernes 18:30',
//           goal: 'Diversión',
//           creationDate: new Date('2025-02-21'),
//           clientId: '30000050',
//         },
//       ],
//       healthData: {
//         clientId: '30000050',
//         healthInsurance: 'Swiss Medical',
//         weight: 74,
//         height: 1.86,
//         currentStudies: '',
//         bloodPressure: '120/80',
//         diseases: '',
//         medications: '',
//         smoker: false,
//         studyImages: [],
//         boneIssues: '',
//       },
//     },
//   ],
// ];
